import { describe, it, expect } from 'vitest'
import { scoreType } from './oejts'
import type { Answers, AnswerValue } from './types'

// Ground truth captured directly from the live OEJTS instrument
// (openpsychometrics.org/tests/OEJTS) on 2026-06-08: each `answers` map was
// POSTed to the source scorer and `expected` is the 4-letter type it returned.
// `id N` == the source's question N, so answers map 1:1. Regenerated by the
// parity harness; if a case ever mismatches, fix the offending item's
// axis/rightLetter in oejts.ts (or the cutoff in AXIS_LETTERS) — not the scorer.
const CASES: { name: string; answers: Answers; expected: string }[] = [
  { name: "all-left (1)", expected: "ESTJ", answers: { 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1, 10: 1, 11: 1, 12: 1, 13: 1, 14: 1, 15: 1, 16: 1, 17: 1, 18: 1, 19: 1, 20: 1, 21: 1, 22: 1, 23: 1, 24: 1, 25: 1, 26: 1, 27: 1, 28: 1, 29: 1, 30: 1, 31: 1, 32: 1 } as Answers },
  { name: "all-right (5)", expected: "INFP", answers: { 1: 5, 2: 5, 3: 5, 4: 5, 5: 5, 6: 5, 7: 5, 8: 5, 9: 5, 10: 5, 11: 5, 12: 5, 13: 5, 14: 5, 15: 5, 16: 5, 17: 5, 18: 5, 19: 5, 20: 5, 21: 5, 22: 5, 23: 5, 24: 5, 25: 5, 26: 5, 27: 5, 28: 5, 29: 5, 30: 5, 31: 5, 32: 5 } as Answers },
  { name: "all-neutral (3)", expected: "INTJ", answers: { 1: 3, 2: 3, 3: 3, 4: 3, 5: 3, 6: 3, 7: 3, 8: 3, 9: 3, 10: 3, 11: 3, 12: 3, 13: 3, 14: 3, 15: 3, 16: 3, 17: 3, 18: 3, 19: 3, 20: 3, 21: 3, 22: 3, 23: 3, 24: 3, 25: 3, 26: 3, 27: 3, 28: 3, 29: 3, 30: 3, 31: 3, 32: 3 } as Answers },
  { name: "random-0", expected: "ENTJ", answers: { 1: 1, 2: 1, 3: 3, 4: 2, 5: 2, 6: 2, 7: 1, 8: 5, 9: 1, 10: 5, 11: 4, 12: 1, 13: 1, 14: 1, 15: 2, 16: 2, 17: 5, 18: 5, 19: 1, 20: 5, 21: 2, 22: 5, 23: 4, 24: 2, 25: 4, 26: 5, 27: 3, 28: 1, 29: 2, 30: 4, 31: 3, 32: 3 } as Answers },
  { name: "random-1", expected: "INTP", answers: { 1: 2, 2: 2, 3: 3, 4: 1, 5: 1, 6: 4, 7: 1, 8: 3, 9: 3, 10: 5, 11: 3, 12: 1, 13: 4, 14: 5, 15: 1, 16: 4, 17: 1, 18: 5, 19: 3, 20: 5, 21: 3, 22: 5, 23: 2, 24: 1, 25: 1, 26: 2, 27: 3, 28: 1, 29: 2, 30: 1, 31: 4, 32: 3 } as Answers },
  { name: "random-2", expected: "ISFJ", answers: { 1: 4, 2: 3, 3: 2, 4: 3, 5: 3, 6: 2, 7: 3, 8: 1, 9: 5, 10: 2, 11: 5, 12: 2, 13: 2, 14: 4, 15: 4, 16: 3, 17: 5, 18: 2, 19: 3, 20: 1, 21: 2, 22: 1, 23: 3, 24: 4, 25: 3, 26: 1, 27: 2, 28: 5, 29: 3, 30: 2, 31: 4, 32: 4 } as Answers },
  { name: "random-3", expected: "ISTJ", answers: { 1: 4, 2: 2, 3: 3, 4: 2, 5: 2, 6: 5, 7: 5, 8: 3, 9: 5, 10: 4, 11: 5, 12: 4, 13: 3, 14: 2, 15: 2, 16: 5, 17: 4, 18: 1, 19: 1, 20: 1, 21: 2, 22: 2, 23: 4, 24: 5, 25: 1, 26: 4, 27: 4, 28: 5, 29: 4, 30: 5, 31: 3, 32: 5 } as Answers },
  { name: "random-4", expected: "ESTJ", answers: { 1: 1, 2: 1, 3: 5, 4: 3, 5: 3, 6: 1, 7: 3, 8: 4, 9: 2, 10: 4, 11: 1, 12: 3, 13: 5, 14: 2, 15: 5, 16: 1, 17: 3, 18: 5, 19: 5, 20: 2, 21: 2, 22: 3, 23: 2, 24: 5, 25: 5, 26: 1, 27: 5, 28: 3, 29: 4, 30: 1, 31: 1, 32: 3 } as Answers },
  { name: "random-5", expected: "ESFP", answers: { 1: 3, 2: 2, 3: 1, 4: 2, 5: 5, 6: 1, 7: 1, 8: 4, 9: 1, 10: 5, 11: 2, 12: 2, 13: 4, 14: 5, 15: 2, 16: 3, 17: 5, 18: 5, 19: 4, 20: 2, 21: 5, 22: 2, 23: 3, 24: 4, 25: 3, 26: 4, 27: 5, 28: 4, 29: 1, 30: 2, 31: 2, 32: 1 } as Answers },
  { name: "random-6", expected: "ESTJ", answers: { 1: 3, 2: 1, 3: 5, 4: 5, 5: 2, 6: 5, 7: 2, 8: 1, 9: 1, 10: 1, 11: 2, 12: 1, 13: 1, 14: 3, 15: 1, 16: 5, 17: 2, 18: 3, 19: 4, 20: 2, 21: 5, 22: 2, 23: 5, 24: 5, 25: 4, 26: 2, 27: 4, 28: 4, 29: 2, 30: 1, 31: 1, 32: 4 } as Answers },
  { name: "random-7", expected: "ENFJ", answers: { 1: 3, 2: 4, 3: 4, 4: 4, 5: 1, 6: 1, 7: 1, 8: 4, 9: 3, 10: 1, 11: 2, 12: 2, 13: 2, 14: 5, 15: 4, 16: 2, 17: 4, 18: 2, 19: 3, 20: 4, 21: 2, 22: 1, 23: 4, 24: 5, 25: 1, 26: 1, 27: 5, 28: 1, 29: 1, 30: 2, 31: 2, 32: 4 } as Answers },
  { name: "random-8", expected: "ESFP", answers: { 1: 4, 2: 4, 3: 2, 4: 4, 5: 1, 6: 2, 7: 4, 8: 1, 9: 4, 10: 3, 11: 4, 12: 3, 13: 4, 14: 5, 15: 4, 16: 2, 17: 2, 18: 3, 19: 2, 20: 1, 21: 5, 22: 5, 23: 1, 24: 3, 25: 1, 26: 1, 27: 5, 28: 4, 29: 5, 30: 5, 31: 2, 32: 1 } as Answers },
  { name: "random-9", expected: "ENTP", answers: { 1: 5, 2: 1, 3: 2, 4: 1, 5: 5, 6: 1, 7: 2, 8: 4, 9: 1, 10: 5, 11: 2, 12: 5, 13: 5, 14: 1, 15: 5, 16: 1, 17: 4, 18: 5, 19: 5, 20: 5, 21: 3, 22: 3, 23: 2, 24: 3, 25: 2, 26: 3, 27: 4, 28: 2, 29: 3, 30: 4, 31: 3, 32: 1 } as Answers },
]

describe('OEJTS parity with the source instrument', () => {
  it.each(CASES)('matches the live test for $name (-> $expected)', ({ answers, expected }) => {
    expect(scoreType(answers)!.type).toBe(expected)
  })

  it('every case answers all 32 items with valid 1..5 values', () => {
    for (const c of CASES) {
      const ids = Object.keys(c.answers).map(Number).sort((a, b) => a - b)
      expect(ids).toEqual(Array.from({ length: 32 }, (_, n) => n + 1))
      for (const v of Object.values(c.answers)) {
        expect(v).toBeGreaterThanOrEqual(1 as AnswerValue)
        expect(v).toBeLessThanOrEqual(5 as AnswerValue)
      }
    }
  })
})
